#pragma once

#define COLUMN_WIDTH 64
#define HIT_FRAMES 10
#define HIT_RATIO 0.3
#define NUM_COLUMNS 4
#define MIN_NUM_TARGETS 4
#define MAX_NUM_TARGETS 10
#define MIN_TARGET_SPEED 100
#define MAX_TARGET_SPEED 200
#define MAX_HIT_DISTANCE 50
#define MISS_PENALTY -10
